---
title: "Enumeration of CMMCs"
author: "Ankit Dutta and JB Alberge"
date: February 16, 2022
output: 
  html_document:
    toc: true
    toc_depth: 2
    df_print: kable
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(cache = FALSE)
```

# Enumeration

```{r}
library(tidyverse)
library(RColorBrewer)
library(cowplot)
library(readxl)
library(circlize)
library(ggpubr)
library(broom)

source("../0_utils/utils.R")
```


```{r}

precursor_cmmcs_counts <- read.csv("data/precursorcmmc_counts.csv")
smm_cmmcs_risk20220 <- read.csv("data/smmcmmc_20220riskFINAL.csv")

mgus.smm.palette <- c("MGUS" = "#72cfed", "SMM" = "#f4793f") # original ankit
# mgus.smm.palette <- c("MGUS" = "#A8D2E0", "SMM" = "#FFDE89")
# mgus.smm.palette <- c("MGUS" = "#5caba8", "SMM" = "#dc5e74") # bordeaux green
# smm.palette <- c("Low"="#009ec0", "Intermediate"="#d9cc25", "High"="#df7726")
smm.palette <- c("Low"="#64B1BB", "Intermediate"="#8AB2BB", "High"="#F0AD00")
# smm.palette <- c("Low"="#eba0ab", "Intermediate"="#dc5e74", "High"="#a94659") # gradient bordeaux

```


## MGUS vs SMM

```{r, fig.width=7, fig.height=4}
basic.stat <- precursor_cmmcs_counts |>
  summarise(N_nonzero = sum(CellRescue>0),
            N_zero = sum(CellRescue==0),
            PCT_zero = percent(N_zero/n()),
            N_nonzero_MGUS = sum(CellRescue>0 & Stage=="MGUS"),
            N_nonzero_SMM = sum(CellRescue>0 & Stage=="SMM"),
            N_participants = n(),
            N_SMM=sum(Stage=="SMM"),
            N_MGUS=sum(Stage=="MGUS"),
            N_5=sum(CellRescue>=5),
            PCT_5=percent(N_5/n()),     
            N_5_SMM=sum(CellRescue>=5 & Stage=="SMM"),
            PCT_5_SMM=percent(N_5_SMM / sum(Stage=="SMM")),
            N_5_MGUS=sum(CellRescue>=5 & Stage=="MGUS"),
            PCT_5_MGUS=percent(N_5_MGUS / sum(Stage=="MGUS")),
            N_50=sum(CellRescue>=50),
            PCT_50=percent(N_50/n()),
            N_300=sum(CellRescue>=300),
            PCT_300=percent(N_300/n()),
            N_50_SMM=sum(CellRescue>=50 & Stage=="SMM"),
            PCT_50_SMM=percent(N_50_SMM / sum(Stage=="SMM")),
            N_300_SMM=sum(CellRescue>=300 & Stage=="SMM"),
            PCT_300_SMM=percent(N_300_SMM/ sum(Stage=="SMM")),
            N_50_MGUS=sum(CellRescue>=50 & Stage=="MGUS"),
            PCT_50_MGUS=percent(N_50_MGUS / sum(Stage=="MGUS")),
            N_300_MGUS=sum(CellRescue>=300 & Stage=="MGUS"),
            PCT_300_MGUS=percent(N_300_MGUS/ sum(Stage=="MGUS")))

basic.stat
```

### Bar plot option 1

```{r, fig.width=4, fig.height=4}
fig.bar.rescue.number <- precursor_cmmcs_counts |>
  mutate(Patient=fct_reorder(as.factor(Patient), -CellRescue)) |>
  ggplot(aes(fct_reorder2(Patient, -CellRescue, Stage), CellRescue,  fill = Stage)) +
  geom_vline(xintercept = c( basic.stat$N_50_SMM, basic.stat$N_SMM+basic.stat$N_50_MGUS ), linetype=2, color="grey50") +
  geom_vline(xintercept = c( basic.stat$N_300_SMM, basic.stat$N_SMM+basic.stat$N_300_MGUS ), linetype=2, color="grey50") +
  geom_bar(stat = "identity", width = 1) +
  geom_segment(x = basic.stat$N_nonzero_SMM+1, xend = basic.stat$N_SMM, y=.2, yend=.2,  size=.2) +
  geom_segment(x = basic.stat$N_SMM+basic.stat$N_nonzero_MGUS+1, xend = basic.stat$N_participants, y=.2, yend=.2,  size=.2) +
  # geom_segment(x = basic.stat$N_50_SMM, xend=basic.stat$N_50_SMM, y=50, yend=1E5) +
  annotate(geom = "text", x = 1/2*(basic.stat$N_nonzero_SMM+1+basic.stat$N_SMM), y=1.5, label=paste0("N=", basic.stat$N_SMM-basic.stat$N_nonzero_SMM),  size=2.5) +
  annotate(geom = "text", x = 1/2*(basic.stat$N_SMM+basic.stat$N_nonzero_MGUS+1+basic.stat$N_participants), y=1.5, label=paste0("N=", basic.stat$N_MGUS-basic.stat$N_nonzero_MGUS), size=2.5) +
  scale_fill_manual(values = mgus.smm.palette) +
  # scale_y_log10(breaks = breaks, minor_breaks = minor_breaks, expand=c(0, 0)) +
  scale_y_continuous(trans = "pseudo_log",
                     breaks = int.breaks,
                     minor_breaks = minor_breaks, 
                     labels = function(x) format(x, big.mark = ",", scientific = FALSE),
                     expand = expansion(mult = c(0, 0.1))) +
  scale_x_discrete(expand = expansion(add = c(2, 0))) +
  labs(x="Participant", y="Number of cells rescued") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = c(.8, .8),
        aspect.ratio = 1,
        # legend.background = element_rect(fill = "white", color = "black"),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank())
fig.bar.rescue.number
```



```{r, fig.width=4, fig.height=4}
# for crossover
fig.bar.rescue.number.crossover <- precursor_cmmcs_counts |>
  mutate(Patient=fct_reorder(as.factor(Patient), -CellRescue)) |>
  ggplot(aes(fct_reorder(Patient, -CellRescue), CellRescue,  fill = Stage)) +
  # geom_vline(xintercept = c( basic.stat$N_50, basic.stat$N_300 ), linetype=2, color="grey50") +
  geom_bar(stat = "identity", width = 1) +
  # geom_segment(x = basic.stat$N_nonzero_SMM+1, xend = basic.stat$N_SMM, y=.2, yend=.2, color="grey", size=.2) +
  # geom_segment(x = basic.stat$N_SMM+basic.stat$N_nonzero_MGUS+1, xend = basic.stat$N_participants, y=.2, yend=.2, color="grey", size=.2) +
   geom_segment(x = basic.stat$N_nonzero+1, xend = basic.stat$N_participants, y=.2, yend=.2,  size=.2) +
   # annotate(geom = "text", x = 1/2*(basic.stat$N_nonzero+1+basic.stat$N_participants), y=2, label=paste0("N=", basic.stat$N_participants-basic.stat$N_nonzero, "\n", basic.stat$PCT_zero, " at\nzero"), size=2.5) +
   annotate(geom = "text", x = 1/2*(basic.stat$N_nonzero+1+basic.stat$N_participants), y=3, label=paste0(basic.stat$PCT_zero, "\nwithout\ncells"), size=2.5) +
  # annotate(geom = "text", x = 1/2*(basic.stat$N_50 + basic.stat$N_300), y = 1E3, label=paste0(basic.stat$PCT_50, "\nover\n50"),  size=2.5) +
  # annotate(geom = "text", x = 1/2*(basic.stat$N_300), y = 3E4, label=paste0(basic.stat$PCT_300, "\nover\n300"), size=2.5) +
  # annotate(geom = "text", x = 1/2*(basic.stat$N_SMM+basic.stat$N_nonzero_MGUS+1+basic.stat$N_participants), y=1.5, label=paste0("N=", basic.stat$N_MGUS-basic.stat$N_nonzero_MGUS), color="grey", size=2.5) +
  scale_fill_manual(values=mgus.smm.palette) +
  # scale_y_log10(breaks = breaks, minor_breaks = minor_breaks, expand=c(0, 0)) +
  scale_y_continuous(trans = "pseudo_log",
                     breaks = int.breaks,
                     minor_breaks = minor_breaks, 
                     labels = function(x) format(x, big.mark = ",", scientific = FALSE),
                     expand = expansion(mult = c(0, 0.1))) +
  scale_x_discrete(expand = expansion(add = c(2, 0))) +
  labs(x=paste0("Participant (n=", basic.stat$N_participants, ")"), y="CTCs count") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = c(.8, .8),
        aspect.ratio = 1,
        # legend.background = element_rect(fill = "white", color = "black"),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank())
fig.bar.rescue.number.crossover
```

# put together
```{r, fig.width=7, fig.height=4}
qts <- c(0, .25, .5, .75, 1)
qts.stat <- precursor_cmmcs_counts |>
  group_by(Stage) |>
  summarise(qts=qts, y=quantile(CellRescue, qts))

mgus.median.label = paste0("N = ", basic.stat$N_MGUS, "\nMedian = ", pull(subset(qts.stat, Stage=="MGUS" & qts==0.5), y))
mgus.median.y = 1.5*pull(subset(qts.stat, Stage=="MGUS" & qts==1), y)

smm.median.label = paste0("N = ", basic.stat$N_SMM, "\nMedian = ", pull(subset(qts.stat, Stage=="SMM" & qts==0.5), y))
smm.median.y = 1.5*pull(subset(qts.stat, Stage=="SMM" & qts==1), y)

fig.violin.rescue.number <- precursor_cmmcs_counts |>
  mutate(Patient=fct_reorder(as.factor(Patient), -CellRescue)) |>
  ggplot(aes(Stage, CellRescue, color=Stage)) +
  geom_violin(scale = "count", adjust=1, width=1.3) +
  geom_jitter(width=0.15, shape=21, alpha=0.5) +
  geom_boxplot(width=0.3, fill=NA) +
  annotate(geom = "text", x = 1.1, label=mgus.median.label, y=mgus.median.y, size=2.5, fontface = 'italic', hjust=0) +
  annotate(geom = "text", x = 2.1, label=smm.median.label, y=smm.median.y, size=2.5, fontface = 'italic', hjust=0) +
  scale_y_continuous(trans = "pseudo_log",
                     breaks = int.breaks,
                     minor_breaks = minor_breaks, 
                     labels = function(x) format(x, big.mark = ",", scientific = FALSE),
                     expand = expansion(mult = c(0, 0.1))) +
  scale_color_manual(values = mgus.smm.palette) +
  labs(x="", y="CTC counts") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = "none",
        aspect.ratio = 1) +
  stat_compare_means(comparisons = list(c("MGUS", "SMM")), hide.ns = TRUE, label = "p.format", tip.length = 0, symnum.args=symnum.args)

# p.fig1bc <- plot_grid(fig.bar.rescue.number, fig.violin.rescue.number, axis = "btlr", align = "hv")
p.fig1bc <- plot_grid(fig.bar.rescue.number.crossover, fig.violin.rescue.number, axis = "btlr", align = "hv")

print(p.fig1bc)
ggsave2("figures/Fig1bc.pdf", p.fig1bc, width = 7, height = 4)
ggsave2("figures/Fig1bc.png", p.fig1bc, width = 7, height = 4, units = "in")

```


## Clinical staging in SMM


```{r fig.width=4, fig.height=4}

smm_cmmcs_risk20220.clean <- smm_cmmcs_risk20220 %>%
  mutate(CellRescue=as.numeric(CellRescue)) %>%
  filter(ID!="MN0084" & X20.2.20.stage!="") %>% # this patient had unsufficient material for enumeration
  mutate(X20.2.20.stage=factor(X20.2.20.stage, levels = c("Low", "Intermediate", "High")))

N.stat.smm <- smm_cmmcs_risk20220.clean |>
  group_by(X20.2.20.stage) |>
  summarise(N=n()) |>
  as.matrix()
qts.stat.smm <- smm_cmmcs_risk20220.clean |>
  group_by(X20.2.20.stage) |>
  summarise(qts=qts, y=quantile(CellRescue, qts))

low.label = paste0("N = ", N.stat.smm[1,2], "\nMedian = ", round(pull(subset(qts.stat.smm, X20.2.20.stage=="Low" & qts==0.5), y)))
low.y = 1.5*pull(subset(qts.stat.smm, X20.2.20.stage=="Low" & qts==1), y)

int.label = paste0("N = ", N.stat.smm[2,2], "\nMedian = ",round( pull(subset(qts.stat.smm, X20.2.20.stage=="Intermediate" & qts==0.5), y)))
int.y = 1*pull(subset(qts.stat.smm, X20.2.20.stage=="Intermediate" & qts==1), y)

high.label = paste0("N = ", N.stat.smm[3,2], "\nMedian = ", round(pull(subset(qts.stat.smm, X20.2.20.stage=="High" & qts==0.5), y)))
high.y = 1.7*pull(subset(qts.stat.smm, X20.2.20.stage=="High" & qts==1), y)

fig.boxplot.2.20.20 <- ggplot(smm_cmmcs_risk20220.clean, aes(X20.2.20.stage, CellRescue, color=X20.2.20.stage)) +
  geom_violin(scale = "width", width=0.9) +
  geom_jitter(width=0.15, shape=21, alpha=0.5) +
  geom_boxplot(width=0.3, fill=NA) +
  annotate(geom = "text", x = 1.1, label=low.label, y=low.y, size=2.5, fontface = 'italic', hjust=0) +
  annotate(geom = "text", x = 2.2, label=int.label, y=int.y, size=2.5, fontface = 'italic', hjust=0) +
  annotate(geom = "text", x = 3, label=high.label, y=high.y, size=2.5, fontface = 'italic', hjust=0.5) +
  scale_y_continuous(trans = "pseudo_log",
                     breaks = int.breaks,
                     minor_breaks = minor_breaks, 
                     labels = function(x) format(x, big.mark = ",", scientific = FALSE),
                     expand = expansion(mult = c(0, 0.1))) +
  scale_color_manual(values = smm.palette) +
  labs(x="20/2/20 Stage", y="CTCs count", fill="") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = "none",
        aspect.ratio = 1) +
  stat_compare_means(comparisons = list(c("Intermediate", "High"), c("Low", "Intermediate"), c("Low", "High")), label = "p.signif",
                      tip.length = 0, p.adjust.method = "fdr",step.increase = 0.06, vjust = 0.5)

print(fig.boxplot.2.20.20)

ggsave2("figures/Fig1d.pdf", fig.boxplot.2.20.20, width = 4, height = 4)
ggsave2("figures/Fig1d.png", fig.boxplot.2.20.20, width = 4, height = 4, units = "in")


```

## Correlation between N CMMCs and 20/2/20 variables
<!-- smm_cmmcs_risk20220 %>% ggplot(aes(x=reorder(X20.2.20.stage,CellRescue,FUN=median), y=CellRescue, fill=X20.2.20.stage, alpha=2)) + geom_boxplot() + scale_fill_manual(values = c("Low"="Steelblue1","Intermediate"="Lightgoldenrod", "High"="Tomato")) + xlab("20-2-20 Risk Stage") + ylab("CMMCs Count") + scale_y_continuous(trans='pseudo_log') + theme_light(base_size = 14) + theme(legend.position ="none", axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) -->

### Enumeration and BM percentage

```{r fig.width=4, fig.height=4}

df <- smm_cmmcs_risk20220 %>% 
  # mutate(BMperc=BM..) %>%
  filter(!is.na(BMperc)) %>%
  mutate(logCTC=log(1+CellRescue),
         logFLC=log(1+FLC.Ratio))

cor.data <- tidy(cor.test(df$logCTC, df$BMperc))
cor.data

BMperc.cor <- df %>%
  ggplot(aes(BMperc, CellRescue)) +
  geom_smooth(method="lm", color="black") +
  annotate(geom="text", label=paste0("R=", signif(cor.data$estimate, 3), "; p=", signif(cor.data$p.value, 1)), x = 15, y=45000, size=3) +
  geom_point() + 
  scale_y_continuous(trans = "pseudo_log", limits=c(0, NA), breaks = breaks, minor_breaks = minor_breaks, labels = scales::number) +  scale_x_continuous(limits=c(0, NA)) +
  theme_bw() +
  labs(x="Bone marrow plasma cell\ninfiltration (%)", 
       y="Circulating multiple myeloma cells\nenumeration (N)") +
  theme(aspect.ratio = 1, panel.grid = element_blank())

print(BMperc.cor)
ggsave("figures/FigS.BMperc.correlation.png", BMperc.cor, height = 4, width = 4)
ggsave("figures/FigS.BMperc.correlation.pdf", BMperc.cor, height = 4, width = 4)
```

### Enumeration and MSpike

```{r fig.width=4, fig.height=4}

cor.data <- tidy(cor.test(df$logCTC, df$M.Spike))
cor.data

MSpike.cor <- df %>%
  ggplot(aes(M.Spike, CellRescue)) +
  geom_smooth(method="lm", color="black") +
  annotate(geom="text", label=paste0("R=", signif(cor.data$estimate, 3), "; p=", signif(cor.data$p.value, 1)), x = 0.5, y=45000, size=3) +
  geom_point() +
  scale_y_continuous(trans = "pseudo_log", limits=c(0, NA), breaks = breaks, minor_breaks = minor_breaks, labels = scales::number) +
  scale_x_continuous(limits=c(0, NA)) +
  labs(x="M-spike (g/dL)", y="Circulating multiple myeloma cells\nenumeration (N)") +
  theme_bw() +
  theme(aspect.ratio = 1, panel.grid = element_blank())

print(MSpike.cor)
ggsave("figures/FigS.MSpike.correlation.png", BMperc.cor, height = 4, width = 4)
ggsave("figures/FigS.MSpike.correlation.pdf", BMperc.cor, height = 4, width = 4)
```


# Eligibility

We showed translocation in as little as to 40 cells at 50% purity

```{r}
precursor_cmmcs_counts %>% 
  filter(Stage=="MGUS") %>% 
  summarise(frac=sum(CellRescue>40)/n())
```

```{r}
precursor_cmmcs_counts %>% 
  filter(Stage=="SMM") %>% 
  summarise(frac=sum(CellRescue>40)/n())
```

```{r}
smm_cmmcs_risk20220.clean %>% 
  filter(X20.2.20.stage=="High") %>% 
  summarise(frac=sum(CellRescue>40)/n())
```
```



# Session info

```{r, eval=TRUE, include=TRUE, comment=NA}
sessionInfo()
```

